image: alpine:latest

pages:
  stage: deploy
  script:
  - apk update && apk add doxygen && apk add graphviz
  - apk add ghostscript
  - mkdir build 
  - cd doc
  - doxygen doxyfile
  - cd ../
  - mv build/html/ public
  - cp doc/customdoxygen.css public/
  - mkdir public/figs/
  - cp doc/figs/*.png public/figs/.
  artifacts:
    paths:
    - public
  only:
  - master
