image: alpine

doxydocumentation:
  script:
  - apk update && apk add doxygen && apk add graphviz
  - cd doc
  - doxygen doxygen.conf
  - mv html/ ../public/
  - cp style.css ../public/
  artifacts:
    paths:
    - public
  only:
  - master
