image: alpine:latest

pages:
  stage: deploy
  script:
  - apk update && apk add doxygen && apk add graphviz
  - apk add texlive-full && apk add ghostscript
  - cd doc
  - doxygen doxygen.conf
  - cd ../
  - mv doc/html/ public
  - cp doc/style.css public/
  - mkdir public/figs/
  - cp doc/figs/*.png public/figs/.
  artifacts:
    paths:
    - public
  only:
  - master
