image: alpine:latest

pages:
  stage: deploy
  script:
  - apk update && apk add doxygen && apk add graphviz && apk add texlive-2018
  - cd doc
  - doxygen doxygen.conf
  - cd ../
  - mv doc/html/ public
  - cp doc/style.css public/
  artifacts:
    paths:
    - public
  only:
  - master
