# This will run on Travis' 'new' container-based infrastructure
sudo: false
dist: trusty

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: AmpGen
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/doxyfile
    - GH_REPO_REF: github.com/GooFit/AmpGen.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
#      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - echo true 

# Generate and deploy documentation
after_success:
  - chmod +x .ci/build_docs.sh
  - source .ci/build_docs.sh
