# This will run on Travis' 'new' container-based infrastructure
sudo: false

cache:
  ccache: true
  apt: true
  directories:
  - "${TRAVIS_BUILD_DIR}/deps/root"
  - "${TRAVIS_BUILD_DIR}/deps/doxygen"

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: AmpGen
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/doxyfile
    - GH_REPO_REF: github.com/GooFit/AmpGen.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - chmod +x .ci/travis.sh
  - source .ci/travis.sh

# Generate and deploy documentation
after_success:
  - chmod +x .ci/build_docs.sh
  - source .ci/build_docs.sh
