sudo: false
# os:
#   - linux
#   - osx
# 
# compiler:
#   - gcc 
#   - clang
matrix: 
  include:
    - os: osx 
      osx_image: xcode10.1
      compiler: clang
    - os: linux
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  


cache:
  ccache: true
  apt: true
  directories:
  - "${TRAVIS_BUILD_DIR}/deps/root"
  - "${TRAVIS_BUILD_DIR}/deps/doxygen"

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: AmpGen
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/doxyfile
    - GH_REPO_REF: github.com/GooFit/AmpGen.git
    - DEPS_DIR: "${TRAVIS_BUILD_DIR}/deps"

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-gui
      - graphviz
      - libtbb-dev
      
before_install:
  - chmod +x .ci/build_root_${TRAVIS_OS_NAME}.sh
  - source .ci/build_root_${TRAVIS_OS_NAME}.sh 

# Build your code e.g. by calling make
script:
  - chmod +x .ci/travis_${TRAVIS_OS_NAME}.sh
  - source .ci/travis_${TRAVIS_OS_NAME}.sh

# Generate and deploy documentation
after_success:
  - chmod +x .ci/build_docs.sh
  - source .ci/build_docs.sh
