name: Make Documentation
on: 
  push: 
    branches: 
      - master
  pull_request: 
    branches:
      - master

jobs: 
  build:
    name: doxygen
    runs-on: ${{ ubuntu-latest }}

  uses: mattnotmitt/doxygen-action@v1
  with:
    doxyfile-path: 'docs'
    enable-latex: true
