name: Precommit
on:
  push: 
    branches: 
      - master
      - v* 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0             # otherwise, you will failed to push refs to dest repo
    - name: "Generate README.md"
      run: python .github/scripts/process_markdown.py README.tex.md README.md 
    - name: Commit files
      run: |
        if git status | grep -q modified; then
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
        else 
          echo "Nothing to do"
        fi

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
